; image assets/tape_error1.png 64x18
msg_tape_error1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $81,$86,$0c,$1c,$10,$60,$e1,$83
	db $e7,$32,$64,$fc,$f3,$26,$4c,$99
	db $e7,$02,$0c,$3c,$30,$60,$cc,$83
	db $e7,$32,$7c,$fc,$f3,$26,$4c,$99
	db $e7,$32,$7c,$1c,$13,$26,$61,$99
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/tape_error2.png 64x18
msg_tape_error2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $81,$86,$0c,$1c,$10,$60,$e1,$83
	db $f3,$99,$32,$7e,$79,$93,$26,$4c
	db $ce,$04,$18,$78,$60,$c1,$99,$07
	db $f3,$99,$3e,$7e,$79,$93,$26,$4c
	db $ce,$64,$f8,$38,$26,$4c,$c3,$33
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/hello1.png 64x18
msg_hello1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$ff,$c9,$04,$e7,$87,$3f,$ff
	db $ff,$ff,$c9,$3c,$e7,$31,$3f,$ff
	db $ff,$ff,$c1,$0c,$e7,$31,$3f,$ff
	db $ff,$ff,$c9,$3c,$e7,$31,$ff,$ff
	db $ff,$ff,$c9,$04,$21,$87,$3f,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/hello2.png 64x18
msg_hello2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$ff,$c4,$83,$73,$81,$bf,$ff
	db $ff,$ff,$c4,$99,$73,$3e,$9f,$ff
	db $ff,$ff,$80,$80,$cf,$2a,$9f,$ff
	db $ff,$ff,$c4,$9f,$73,$3e,$ff,$ff
	db $ff,$ff,$c4,$83,$10,$81,$bf,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/all_my_cycles.png 64x18
msg_all_my_cycles:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e1,$99,$e7,$53,$89,$31,$39,$c7
	db $8c,$99,$e2,$53,$39,$27,$26,$9f
	db $80,$99,$e5,$43,$38,$27,$20,$87
	db $8c,$99,$e7,$73,$3f,$27,$33,$f9
	db $8c,$88,$67,$4f,$8c,$71,$08,$c1
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/used_to_be.png 64x18
msg_used_to_be:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $fc,$d8,$c7,$38,$63,$e3,$cf,$ff
	db $fc,$d3,$93,$3c,$c9,$e5,$a7,$ff
	db $fc,$98,$c6,$3c,$c9,$e1,$87,$ff
	db $fc,$9e,$5c,$bc,$c9,$e6,$bf,$ff
	db $ff,$18,$e6,$3c,$e3,$e0,$8f,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/blitting.png 64x18
msg_blitting:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$f8,$33,$21,$09,$33,$8f,$ff
	db $ff,$f9,$93,$f3,$9f,$12,$7f,$ff
	db $ff,$f8,$33,$33,$99,$02,$7f,$ff
	db $ff,$f9,$93,$33,$99,$22,$67,$ff
	db $ff,$f8,$31,$33,$99,$33,$87,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/and_i_was_mute.png 64x18
msg_and_i_was_mute:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e7,$f1,$e7,$33,$f8,$f3,$bc,$23
	db $d3,$f2,$ff,$33,$13,$f1,$3f,$6f
	db $d2,$32,$e7,$3a,$58,$f2,$ad,$67
	db $c2,$d2,$e7,$2a,$5e,$73,$ad,$6f
	db $d2,$d1,$e7,$d7,$18,$f3,$b1,$63
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/now_i_unpack.png 64x18
msg_now_i_unpack:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $cd,$9c,$e7,$39,$ad,$1c,$62,$4f
	db $c5,$65,$e7,$3d,$a5,$6a,$4e,$4f
	db $c9,$65,$27,$39,$a9,$68,$4e,$1f
	db $cd,$64,$a7,$39,$ad,$1a,$4e,$4f
	db $cc,$9c,$c7,$3c,$25,$32,$62,$67
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/14_reg_streams.png 64x18
msg_14_reg_streams:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ce,$38,$c6,$3c,$d8,$cc,$ce,$63
	db $cc,$39,$5c,$f9,$da,$5a,$44,$4f
	db $c9,$38,$cc,$fc,$88,$c8,$4a,$67
	db $c8,$39,$5c,$9e,$5a,$5a,$4e,$73
	db $cf,$39,$46,$18,$ca,$4a,$4e,$47
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/on_the_fly.png 64x18
msg_on_the_fly:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$e3,$67,$39,$be,$16,$5f,$ff
	db $ff,$cd,$27,$32,$be,$76,$5f,$ff
	db $ff,$cd,$47,$10,$8e,$27,$1f,$ff
	db $ff,$cd,$67,$3b,$a6,$67,$df,$ff
	db $ff,$e3,$67,$88,$a6,$61,$3f,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/i_am_no_longer.png 64x18
msg_i_am_no_longer:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ce,$17,$33,$33,$99,$99,$8c,$23
	db $cc,$92,$31,$25,$92,$99,$3d,$e5
	db $cc,$95,$32,$25,$92,$89,$3c,$43
	db $cc,$17,$33,$25,$92,$91,$25,$cd
	db $cc,$97,$33,$33,$89,$99,$84,$4d
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/oblitterated.png 64x18
msg_oblitterated:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e3,$0c,$c8,$42,$10,$e3,$08,$f3
	db $c9,$24,$fc,$e6,$72,$49,$99,$c3
	db $c9,$0c,$cc,$e6,$10,$c1,$98,$93
	db $c9,$24,$cc,$e6,$72,$49,$99,$93
	db $e3,$0c,$4c,$e6,$12,$49,$98,$c3
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/an_unlikely.png 64x18
msg_an_unlikely:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $cd,$b6,$b5,$5a,$55,$bb,$37,$6a
	db $b4,$b6,$95,$d6,$d5,$92,$da,$ea
	db $b5,$36,$a5,$4e,$59,$aa,$1d,$e2
	db $85,$b6,$b5,$d6,$dd,$ba,$da,$ea
	db $b5,$b9,$b4,$5a,$49,$ba,$d7,$6a
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/headroom_incident.png 64x18
msg_headroom_incident:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $67,$a7,$39,$bb,$2d,$97,$66,$d1
	db $db,$aa,$d6,$93,$e5,$7e,$5a,$5b
	db $42,$26,$d6,$ab,$29,$75,$46,$9b
	db $da,$aa,$d6,$bb,$2d,$75,$5e,$db
	db $5a,$2b,$39,$bb,$2d,$96,$66,$db
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/svo2022.png 64x18
msg_svo2022:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$c6,$4c,$7e,$1c,$61,$87,$ff
	db $ff,$9e,$49,$3f,$c9,$3c,$f3,$ff
	db $ff,$c6,$49,$3f,$89,$30,$c3,$ff
	db $ff,$f2,$49,$3e,$79,$27,$9f,$ff
	db $ff,$c6,$1c,$7e,$0c,$60,$83,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/music_by.png 64x18
msg_music_by:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e7,$26,$63,$31,$f8,$e7,$23,$31
	db $e2,$26,$4f,$e7,$99,$52,$76,$92
	db $e5,$26,$63,$27,$f8,$d2,$76,$92
	db $e7,$26,$79,$27,$99,$52,$76,$91
	db $e7,$38,$e3,$31,$f8,$e7,$37,$33
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/firestarter1.png 64x18
msg_firestarter1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $8f,$c4,$8c,$62,$33,$18,$88,$ff
	db $9e,$4f,$94,$cf,$69,$2d,$99,$7f
	db $9c,$c4,$8c,$67,$61,$1d,$88,$ff
	db $99,$cc,$94,$f3,$69,$2d,$99,$7f
	db $9f,$cc,$94,$47,$69,$2d,$89,$7f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/firestarter2.png 64x18
msg_firestarter2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $8f,$c4,$8c,$62,$33,$18,$88,$ff
	db $9e,$1f,$29,$9e,$d2,$5b,$32,$ff
	db $9c,$c4,$8c,$67,$61,$1d,$88,$ff
	db $99,$cc,$94,$f3,$69,$2d,$99,$3f
	db $9f,$cc,$94,$47,$69,$2d,$89,$7f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/no_longer_inv1.png 64x18
msg_no_longer_inv1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $06,$66,$70,$cc,$66,$77,$9c,$60
	db $0c,$76,$d8,$db,$66,$c6,$1a,$30
	db $0c,$6e,$d8,$db,$76,$c7,$9c,$30
	db $0c,$66,$d8,$db,$6e,$da,$1a,$30
	db $06,$66,$70,$ee,$66,$7b,$da,$60
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/no_longer_inv2.png 64x18
msg_no_longer_inv2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $06,$66,$70,$cc,$66,$77,$9c,$60
	db $06,$3b,$6c,$6d,$b3,$63,$0d,$18
	db $0c,$6e,$d8,$db,$76,$c7,$9c,$30
	db $18,$cd,$b1,$b6,$dd,$b4,$34,$60
	db $06,$66,$70,$ee,$66,$7b,$da,$60
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
