; image assets/tape_error1.png 64x18
msg_tape_error1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $81,$86,$0c,$1c,$10,$60,$e1,$83
	db $e7,$32,$64,$fc,$f3,$26,$4c,$99
	db $e7,$02,$0c,$3c,$30,$60,$cc,$83
	db $e7,$32,$7c,$fc,$f3,$26,$4c,$99
	db $e7,$32,$7c,$1c,$13,$26,$61,$99
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/tape_error2.png 64x18
msg_tape_error2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $81,$86,$0c,$1c,$10,$60,$e1,$83
	db $f3,$99,$32,$7e,$79,$93,$26,$4c
	db $ce,$04,$18,$78,$60,$c1,$99,$07
	db $f3,$99,$3e,$7e,$79,$93,$26,$4c
	db $ce,$64,$f8,$38,$26,$4c,$c3,$33
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/hello1.png 64x18
msg_hello1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$ff,$c9,$04,$e7,$87,$3f,$ff
	db $ff,$ff,$c9,$3c,$e7,$31,$3f,$ff
	db $ff,$ff,$c1,$0c,$e7,$31,$3f,$ff
	db $ff,$ff,$c9,$3c,$e7,$31,$ff,$ff
	db $ff,$ff,$c9,$04,$21,$87,$3f,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/hello2.png 64x18
msg_hello2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$ff,$c4,$83,$73,$81,$bf,$ff
	db $ff,$ff,$c4,$99,$73,$3e,$9f,$ff
	db $ff,$ff,$80,$80,$cf,$2a,$9f,$ff
	db $ff,$ff,$c4,$9f,$73,$3e,$ff,$ff
	db $ff,$ff,$c4,$83,$10,$81,$bf,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/what_a_strange.png 64x18
msg_what_a_strange:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $99,$7c,$8e,$3c,$5f,$93,$b1,$87
	db $99,$52,$dc,$99,$d9,$51,$a7,$bf
	db $99,$10,$dc,$1c,$cb,$12,$a7,$8f
	db $95,$52,$dc,$9e,$5b,$53,$24,$bf
	db $83,$52,$dc,$98,$cb,$53,$b0,$87
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/place_i_have_to.png 64x18
msg_place_i_have_to:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $8c,$e7,$18,$e7,$99,$66,$93,$1f
	db $94,$d2,$72,$67,$f9,$4a,$97,$b3
	db $94,$c2,$70,$e7,$99,$4a,$93,$ad
	db $8c,$d2,$73,$ff,$98,$43,$17,$ad
	db $9c,$53,$18,$e7,$99,$4b,$91,$b3
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/blit_myself.png 64x18
msg_blit_myself:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e7,$99,$0f,$39,$26,$38,$ce,$1f
	db $e1,$9f,$9f,$11,$24,$f2,$4e,$7f
	db $e4,$99,$9f,$29,$26,$30,$ce,$3f
	db $e4,$99,$9f,$39,$cf,$93,$ce,$7f
	db $e1,$89,$9f,$39,$ce,$38,$c2,$7f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/as_fast_as_i_can.png 64x18
msg_as_fast_as_i_can:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ce,$61,$19,$9f,$f9,$e7,$98,$d9
	db $b4,$e7,$53,$0e,$33,$ff,$36,$c9
	db $86,$62,$19,$9d,$b9,$ef,$30,$51
	db $b7,$66,$dc,$9d,$bc,$ef,$36,$59
	db $b4,$e6,$d9,$ce,$51,$e7,$96,$59
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/just_to_stay.png 64x18
msg_just_to_stay:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e7,$f8,$9f,$0c,$7e,$18,$46,$6f
	db $fc,$93,$8f,$d9,$3c,$fc,$d6,$6f
	db $e4,$99,$9f,$d9,$3c,$3c,$87,$0f
	db $e4,$9c,$9f,$d9,$3f,$c4,$93,$ef
	db $ce,$23,$c7,$dc,$78,$1c,$93,$1f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/where_i_am.png 64x18
msg_where_i_am:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $f3,$aa,$21,$8f,$9f,$04,$e7,$3f
	db $f3,$aa,$e9,$27,$9f,$24,$47,$3f
	db $f2,$a2,$63,$07,$9e,$04,$a7,$3f
	db $f2,$2a,$e9,$3f,$9e,$64,$e7,$ff
	db $f0,$6a,$29,$8f,$9e,$64,$e7,$3f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/i_am_fully.png 64x18
msg_i_am_fully:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $f3,$c2,$73,$e1,$24,$cc,$9f,$ff
	db $f3,$92,$23,$e7,$24,$cc,$9f,$ff
	db $f3,$92,$53,$e3,$24,$ce,$1f,$ff
	db $f3,$82,$73,$e7,$24,$cf,$9f,$ff
	db $f3,$92,$73,$e7,$8c,$46,$79,$27
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/oblitterated.png 64x18
msg_oblitterated:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e3,$0c,$c8,$42,$10,$e3,$08,$f3
	db $c9,$24,$fc,$e6,$72,$49,$99,$c3
	db $c9,$0c,$cc,$e6,$10,$c1,$98,$93
	db $c9,$24,$cc,$e6,$72,$49,$99,$93
	db $e3,$0c,$4c,$e6,$12,$49,$98,$c3
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/an_unlikely.png 64x18
msg_an_unlikely:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $cd,$b6,$b5,$5a,$55,$bb,$37,$6a
	db $b4,$b6,$95,$d6,$d5,$92,$da,$ea
	db $b5,$36,$a5,$4e,$59,$aa,$1d,$e2
	db $85,$b6,$b5,$d6,$dd,$ba,$da,$ea
	db $b5,$b9,$b4,$5a,$49,$ba,$d7,$6a
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/headroom_incident.png 64x18
msg_headroom_incident:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $67,$a7,$39,$bb,$2d,$97,$66,$d1
	db $db,$aa,$d6,$93,$e5,$7e,$5a,$5b
	db $42,$26,$d6,$ab,$29,$75,$46,$9b
	db $da,$aa,$d6,$bb,$2d,$75,$5e,$db
	db $5a,$2b,$39,$bb,$2d,$96,$66,$db
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/svo2022.png 64x18
msg_svo2022:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $ff,$c6,$4c,$7e,$1c,$61,$87,$ff
	db $ff,$9e,$49,$3f,$c9,$3c,$f3,$ff
	db $ff,$c6,$49,$3f,$89,$30,$c3,$ff
	db $ff,$f2,$49,$3e,$79,$27,$9f,$ff
	db $ff,$c6,$1c,$7e,$0c,$60,$83,$ff
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/music_by.png 64x18
msg_music_by:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $e7,$26,$63,$31,$f8,$e7,$23,$31
	db $e2,$26,$4f,$e7,$99,$52,$76,$92
	db $e5,$26,$63,$27,$f8,$d2,$76,$92
	db $e7,$26,$79,$27,$99,$52,$76,$91
	db $e7,$38,$e3,$31,$f8,$e7,$37,$33
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/firestarter1.png 64x18
msg_firestarter1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $8f,$c4,$8c,$62,$33,$18,$88,$ff
	db $9e,$4f,$94,$cf,$69,$2d,$99,$7f
	db $9c,$c4,$8c,$67,$61,$1d,$88,$ff
	db $99,$cc,$94,$f3,$69,$2d,$99,$7f
	db $9f,$cc,$94,$47,$69,$2d,$89,$7f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/firestarter2.png 64x18
msg_firestarter2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $8f,$c4,$8c,$62,$33,$18,$88,$ff
	db $9e,$1f,$29,$9e,$d2,$5b,$32,$ff
	db $9c,$c4,$8c,$67,$61,$1d,$88,$ff
	db $99,$cc,$94,$f3,$69,$2d,$99,$3f
	db $9f,$cc,$94,$47,$69,$2d,$89,$7f
	db $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/no_longer_inv1.png 64x18
msg_no_longer_inv1:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $06,$66,$70,$cc,$66,$77,$9c,$60
	db $0c,$76,$d8,$db,$66,$c6,$1a,$30
	db $0c,$6e,$d8,$db,$76,$c7,$9c,$30
	db $0c,$66,$d8,$db,$6e,$da,$1a,$30
	db $06,$66,$70,$ee,$66,$7b,$da,$60
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
; image assets/no_longer_inv2.png 64x18
msg_no_longer_inv2:	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $06,$66,$70,$cc,$66,$77,$9c,$60
	db $06,$3b,$6c,$6d,$b3,$63,$0d,$18
	db $0c,$6e,$d8,$db,$76,$c7,$9c,$30
	db $18,$cd,$b1,$b6,$dd,$b4,$34,$60
	db $06,$66,$70,$ee,$66,$7b,$da,$60
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
